version: "3.3"

# Obj 1.1
networks:
  mynet:
    driver: bridge

# Whole code block is for Obj 1.2
services:

  # This isMariaDB, named "mysql"
  mysql:

    # Obj 2.1 - specify the latest image
    image: mariadb:latest
    # Obj 2.2
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    # Obj 2.3
    networks:
      - mynet

  # This is redis, named myredis
  myredis:

    # Obj 3.1
    image: redis:latest
    # Obj 3.2
    networks:
      - mynet

  # This is php-fpm, named myphp
  myphp:

    # Obj 4.1
    build:
      context: ./src
      dockerfile: php/dockerfile
    # Obj 4.2
    container_name: myphp
    # Obj 4.3
    ports:
      - "9000:9000"
    # Obj 4.4
    volumes:
      - ./src:/var/www/html
    # Obj 4.5
    depends_on:
      # specify MariaDB:mysql
      - mysql
      # sprcify Redis:myredis
      - myredis
    # Obj 4.6
    networks:
      - mynet

  # This is nginx, named mynginx
  mynginx:

    # Obj 5.1
    image: nginx:latest
    # Obj 5.2 
    ports:
      - "8080:80"
    volumes:
      # Obj 5.3
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      # Obj 5.4
      - ./src/index.html:/var/www/html/index.html
      - ./src/index.php:/var/www/html/index.php
      - ./src/order.php:/var/www/html/order.php
      - ./src/process.php:/var/www/html/process.php
    # Obj 5.5
    depends_on:
      - myphp
    # Obj 5.6
    networks:
      - mynet

  # This is phpMyAdmin, named phpmyadmin
  phpmyadmin:
    # Obj 6.1
    image: phpmyadmin/phpmyadmin:latest
    # Obj 6.2
    ports:
      - "8082:80"
    # Obj 6.3
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: php
      PMA_PASSWORD: php
    depends_on:
      - mysql
    # Obj 6.4
    networks:
      - mynet