FROM php:8.2-fpm

# install need extension
RUN apt-get update && apt-get install -y \
    libzip-dev \
    && pecl install igbinary redis \
    && docker-php-ext-enable igbinary redis \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli

WORKDIR /var/www/html
EXPOSE 9000
CMD ["php-fpm"]